version: "3.8"

services:
  controle_bens_backend:
    depends_on:
      - controle_bens_db
    networks:
      - backend_network
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATA_URL=jdbc:postgresql://controle_bens_db:5432/controle_bens
      - DATA_USERNAME=postgres
      - DATA_PASS=root
  controle_bens_db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=controle_bens
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  db_data:
    name: controle_bens_db_data
networks:
  backend_network:
    driver: bridge
